name: 'Build Release'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Changelog
        run: echo -e "# CHANGELOG\n---\n$COMMIT_MSG" > $CHANGELOG
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          CHANGELOG: ${{ github.workspace }}-CHANGELOG.txt

      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}